export default {
  'Science': undefined,
  'Technology': undefined,
  'Engineering': undefined,
  'Medicine': undefined,
  'Math': undefined,
  'Art': undefined,
  'History': undefined,
  'Gaming': undefined,
  'Animation': undefined,
  'Music': undefined,
  'Sports': undefined,
  'Design': undefined,
  'Literature': undefined,
  'Foods': undefined,
  'Automotive': undefined,
};
