/**
 * Data scraped from https://en.wikipedia.org/wiki/List_of_hobbies
 */
export default {
  '3D printing': undefined,
  'Acroyoga': undefined,
  'Playing piano': undefined,
  'Playing guitar': undefined,
  'Acting': undefined,
  'Aerial silk': undefined,
  'Airbrushing': undefined,
  'Amateur radio': undefined,
  'Animation': undefined,
  'Aquascaping': undefined,
  'Art': undefined,
  'Astrology': undefined,
  'Babysitting': undefined,
  'Baking': undefined,
  'Basketball': undefined,
  'Baton twirling': undefined,
  'Beatboxing': undefined,
  'Beer tasting': undefined,
  'Binge-watching': undefined,
  'Blogging': undefined,
  'Board/tabletop games': undefined,
  'Book discussion clubs': undefined,
  'Book restoration': undefined,
  'Bowling': undefined,
  'Brazilian jiu-jitsu': undefined,
  'Breadmaking': undefined,
  'Building': undefined,
  'Bullet journaling': undefined,
  'Calligraphy': undefined,
  'Candle making': undefined,
  'Candy making': undefined,
  'Car fixing & building': undefined,
  'Card games': undefined,
  'Cardistry': undefined,
  'Ceramics': undefined,
  'Chatting': undefined,
  'Cheesemaking': undefined,
  'Chess': undefined,
  'Cleaning': undefined,
  'Clothesmaking': undefined,
  'Coffee roasting': undefined,
  'Collecting': undefined,
  'Coloring': undefined,
  'Communication': undefined,
  'Community activism': undefined,
  'Computer programming': undefined,
  'Confectionery': undefined,
  'Conlanging': undefined,
  'Construction': undefined,
  'Cooking': undefined,
  'Cosplaying': undefined,
  'Couch surfing': undefined,
  'Couponing': undefined,
  'Craft': undefined,
  'Creative writing': undefined,
  'Crocheting': undefined,
  'Cross-stitch': undefined,
  'Crossword puzzles': undefined,
  'Cryptography': undefined,
  'Cue sports': undefined,
  'Dance': undefined,
  'Decorating': undefined,
  'Digital arts': undefined,
  'Dining': undefined,
  'Diorama': undefined,
  'Distro Hopping': undefined,
  'Diving': undefined,
  'Djembe': undefined,
  'DJing': undefined,
  'Do it yourself': undefined,
  'Drama': undefined,
  'Drawing': undefined,
  'Drink mixing': undefined,
  'Electronic games': undefined,
  'Electronics': undefined,
  'Embroidery': undefined,
  'Engraving': undefined,
  'Entertaining': undefined,
  'Experimenting': undefined,
  'Fantasy sports': undefined,
  'Fashion': undefined,
  'Fashion design': undefined,
  'Feng shui decorating': undefined,
  'Filmmaking': undefined,
  'Fingerpainting': undefined,
  'Fishfarming': undefined,
  'Fishkeeping': undefined,
  'Flower arranging': undefined,
  'Fly tying': undefined,
  'Foreign language learning': undefined,
  'Furniture building': undefined,
  'Gaming': undefined,
  'Genealogy': undefined,
  'Gingerbread house making': undefined,
  'Giving advice': undefined,
  'Glassblowing': undefined,
  'Gardening': undefined,
  'Gongfu tea': undefined,
  'Graphic design': undefined,
  'Gunsmithing': undefined,
  'Gymnastics': undefined,
  'Hacking': undefined,
  'Hardware': undefined,
  'Herp keeping': undefined,
  'Home improvement': undefined,
  'Homebrewing': undefined,
  'Houseplant care': undefined,
  'Hula hooping': undefined,
  'Humor': undefined,
  'Hydroponics': undefined,
  'Ice skating': undefined,
  'Inventing': undefined,
  'Jewelry making': undefined,
  'Jigsaw puzzles': undefined,
  'Journaling': undefined,
  'Juggling': undefined,
  'Karaoke': undefined,
  'Karate': undefined,
  'Kendama': undefined,
  'Knife making': undefined,
  'Knitting': undefined,
  'Knot tying': undefined,
  'Kombucha brewing': undefined,
  'Kung fu': undefined,
  'Lace making': undefined,
  'Lapidary': undefined,
  'Leather crafting': undefined,
  'Lego building': undefined,
  'Livestreaming': undefined,
  'Listening to music': undefined,
  'Listening to podcasts': undefined,
  'Lock picking': undefined,
  'Machining': undefined,
  'Macrame': undefined,
  'Magic': undefined,
  'Makeup': undefined,
  'Massaging': undefined,
  'Mazes (indoor/outdoor)': undefined,
  'Mechanics': undefined,
  'Meditation': undefined,
  'Memory training': undefined,
  'Metalworking': undefined,
  'Miniature art': undefined,
  'Minimalism': undefined,
  'Model building': undefined,
  'Model engineering': undefined,
  'Music': undefined,
  'Nail art': undefined,
  'Needlepoint': undefined,
  'Origami': undefined,
  'Painting': undefined,
  'Palmistry': undefined,
  'Performance': undefined,
  'Pet': undefined,
  'Pet adoption & fostering': undefined,
  'Pet sitting': undefined,
  'Philately': undefined,
  'Photography': undefined,
  'Pilates': undefined,
  'Planning': undefined,
  'Plastic art': undefined,
  'Playing musical instruments': undefined,
  'Poetry': undefined,
  'Poi': undefined,
  'Pole dancing': undefined,
  'Postcrossing': undefined,
  'Pottery': undefined,
  'Powerlifting': undefined,
  'Practical jokes': undefined,
  'Pressed flower craft': undefined,
  'Proofreading and editing': undefined,
  'Proverbs': undefined,
  'Public speaking': undefined,
  'Puppetry': undefined,
  'Puzzles': undefined,
  'Pyrography': undefined,
  'Quilling': undefined,
  'Quilting': undefined,
  'Quizzes': undefined,
  'Radio-controlled model playing': undefined,
  'Rail transport modeling': undefined,
  'Rapping': undefined,
  'Reading': undefined,
  'Recipe creation': undefined,
  'Refinishing': undefined,
  'Reiki': undefined,
  'Reviewing Gadgets': undefined,
  'Robot combat': undefined,
  'Rubik\'s Cube': undefined,
  'Scrapbooking': undefined,
  'Scuba Diving': undefined,
  'Sculpting': undefined,
  'Sewing': undefined,
  'Shoemaking': undefined,
  'Singing': undefined,
  'Sketching': undefined,
  'Skipping rope': undefined,
  'Slot car': undefined,
  'Soapmaking': undefined,
  'Social media': undefined,
  'Spreadsheets': undefined,
  'Sleeping': undefined,
  'Stamp collecting': undefined,
  'Stand-up comedy': undefined,
  'Storytelling': undefined,
  'Stripping': undefined,
  'Sudoku': undefined,
  'Table tennis playing': undefined,
  'Talking': undefined,
  'Tapestry': undefined,
  'Tarot': undefined,
  'Tatebanko': undefined,
  'Tattooing': undefined,
  'Taxidermy': undefined,
  'Telling jokes': undefined,
  'Thrifting': undefined,
  'Upcycling': undefined,
  'Video editing': undefined,
  'Video game developing': undefined,
  'Video gaming': undefined,
  'Video making': undefined,
  'VR Gaming': undefined,
  'Wargaming': undefined,
  'Watch making': undefined,
  'Watching documentaries': undefined,
  'Watching movies': undefined,
  'Watching television': undefined,
  'Wax sealing': undefined,
  'Waxing': undefined,
  'Weaving': undefined,
  'Webtooning': undefined,
  'Weight training': undefined,
  'Welding': undefined,
  'Whisky': undefined,
  'Whittling': undefined,
  'Wikipedia editing': undefined,
  'Wine tasting': undefined,
  'Winemaking': undefined,
  'Witchcraft': undefined,
  'Wood carving': undefined,
  'Woodworking': undefined,
  'Word searches': undefined,
  'Worldbuilding': undefined,
  'Writing': undefined,
  'Writing music': undefined,
  'Yo-yoing': undefined,
  'Yoga': undefined,
  'Zumba': undefined,
  'Air sports': undefined,
  'Airsoft': undefined,
  'Amateur geology': undefined,
  'Amusement park visiting': undefined,
  'Archery': undefined,
  'Auto detailing': undefined,
  'Automobilism': undefined,
  'Astronomy': undefined,
  'Backpacking': undefined,
  'Badminton': undefined,
  'BASE jumping': undefined,
  'Baseball': undefined,
  'Beachcombing': undefined,
  'Beekeeping': undefined,
  'Birdwatching': undefined,
  'Blacksmithing': undefined,
  'BMX': undefined,
  'Board sports': undefined,
  'Bodybuilding': undefined,
  'Bonsai': undefined,
  'Butterfly watching': undefined,
  'Bus riding': undefined,
  'Camping': undefined,
  'Canoeing': undefined,
  'Canyoning': undefined,
  'Car riding': undefined,
  'Car tuning': undefined,
  'Caving': undefined,
  'City trip': undefined,
  'Climbing': undefined,
  'Composting': undefined,
  'Cycling': undefined,
  'Dandyism': undefined,
  'Dog training': undefined,
  'Dog walking': undefined,
  'Dowsing': undefined,
  'Driving': undefined,
  'Farming': undefined,
  'Fishing': undefined,
  'Flag football': undefined,
  'Flower growing': undefined,
  'Flying': undefined,
  'Flying disc': undefined,
  'Flying model planes': undefined,
  'Foraging': undefined,
  'Fossicking': undefined,
  'Freestyle football': undefined,
  'Fruit picking': undefined,
  'Geocaching': undefined,
  'Ghost hunting': undefined,
  'Gold prospecting': undefined,
  'Graffiti': undefined,
  'Groundhopping': undefined,
  'Guerrilla gardening': undefined,
  'Handball': undefined,
  'Herbalism': undefined,
  'Herping': undefined,
  'High-power rocketry': undefined,
  'Hiking': undefined,
  'Hobby horsing': undefined,
  'Hobby tunneling': undefined,
  'Hooping': undefined,
  'Horseback riding': undefined,
  'Hunting': undefined,
  'Inline skating': undefined,
  'Jogging': undefined,
  'Jumping rope': undefined,
  'Karting': undefined,
  'Kayaking': undefined,
  'Kite flying': undefined,
  'Kitesurfing': undefined,
  'Lacrosse': undefined,
  'LARPing': undefined,
  'Letterboxing': undefined,
  'Lomography': undefined,
  'Longboarding': undefined,
  'Martial arts': undefined,
  'Metal detecting': undefined,
  'Motorcycling': undefined,
  'Meteorology': undefined,
  'Motor sports': undefined,
  'Mountain biking': undefined,
  'Mountaineering': undefined,
  'Museum visiting': undefined,
  'Mushroom hunting': undefined,
  'Netball': undefined,
  'Noodling': undefined,
  'Nordic skating': undefined,
  'Orienteering': undefined,
  'Paintball': undefined,
  'Paragliding': undefined,
  'Parkour': undefined,
  'Pickleball': undefined,
  'Picnicking': undefined,
  'Podcast hosting': undefined,
  'Polo': undefined,
  'Public transport riding': undefined,
  'Qigong': undefined,
  'Rafting': undefined,
  'Railway journeys': undefined,
  'Rappelling': undefined,
  'Renaissance fair': undefined,
  'Renovating': undefined,
  'Road biking': undefined,
  'Rock climbing': undefined,
  'Rock painting': undefined,
  'Roller skating': undefined,
  'Rugby': undefined,
  'Running': undefined,
  'Sailing': undefined,
  'Sand art': undefined,
  'Scouting': undefined,
  'Scuba diving': undefined,
  'Sculling': undefined,
  'Shooting': undefined,
  'Shopping': undefined,
  'Shuffleboard': undefined,
  'Skateboarding': undefined,
  'Skiing': undefined,
  'Skimboarding': undefined,
  'Skydiving': undefined,
  'Slacklining': undefined,
  'Sledding': undefined,
  'Snorkeling': undefined,
  'Snowboarding': undefined,
  'Snowmobiling': undefined,
  'Snowshoeing': undefined,
  'Soccer': undefined,
  'Stone skipping': undefined,
  'Storm chasing': undefined,
  'Sun bathing': undefined,
  'Surfing': undefined,
  'Survivalism': undefined,
  'Swimming': undefined,
  'Taekwondo': undefined,
  'Tai chi': undefined,
  'Tennis': undefined,
  'Thru-hiking': undefined,
  'Topiary': undefined,
  'Tourism': undefined,
  'Trade fair visiting': undefined,
  'Travel': undefined,
  'Unicycling': undefined,
  'Urban exploration': undefined,
  'Vacation': undefined,
  'Vegetable farming': undefined,
  'Vehicle restoration': undefined,
  'Videography': undefined,
  'Volunteering': undefined,
  'Walking': undefined,
  'Water sports': undefined,
  'Zoo visiting': undefined,
  'Archaeology': undefined,
  'Biology': undefined,
  'Business': undefined,
  'Chemistry': undefined,
  'Electrochemistry': undefined,
  'English': undefined,
  'Geography': undefined,
  'History': undefined,
  'Mathematics': undefined,
  'Medical science': undefined,
  'Microbiology': undefined,
  'Mycology': undefined,
  'Philosophy': undefined,
  'Physics': undefined,
  'Psychology': undefined,
  'Railway studies': undefined,
  'Research': undefined,
  'Science and technology studies': undefined,
  'Social studies': undefined,
  'Sociology': undefined,
  'Sports science': undefined,
  'Life Science': undefined,
  'Teaching': undefined,
  'Web design': undefined,
  'Action figure': undefined,
  'Antiquing': undefined,
  'Ant-keeping': undefined,
  'Art collecting': undefined,
  'Book collecting': undefined,
  'Button collecting': undefined,
  'Cartophily': undefined,
  'Coin collecting': undefined,
  'Comic book collecting': undefined,
  'Compact discs': undefined,
  'Credit card': undefined,
  'Crystals': undefined,
  'Deltiology': undefined,
  'Die-cast toy': undefined,
  'Digital hoarding': undefined,
  'Dolls': undefined,
  'Element collecting': undefined,
  'Ephemera collecting': undefined,
  'Films': undefined,
  'Fingerprint collecting': undefined,
  'Fusilately': undefined,
  'Knife collecting': undefined,
  'Lotology': undefined,
  'Movie memorabilia collecting': undefined,
  'Perfume': undefined,
  'Phillumeny': undefined,
  'Radio-controlled model collecting': undefined,
  'Rail transport modelling': undefined,
  'Record collecting': undefined,
  'Rock tumbling': undefined,
  'Scutelliphily': undefined,
  'Shoes': undefined,
  'Sports memorabilia': undefined,
  'Stuffed toy collecting': undefined,
  'Tea bag collecting': undefined,
  'Ticket collecting': undefined,
  'Transit map collecting': undefined,
  'Video game collecting': undefined,
  'Vintage cars': undefined,
  'Vintage clothing': undefined,
  'Vinyl Records': undefined,
  'Antiquities': undefined,
  'Auto audiophilia': undefined,
  'Flower collecting and pressing': undefined,
  'Fossil hunting': undefined,
  'Insect collecting': undefined,
  'Leaves': undefined,
  'Magnet fishing': undefined,
  'Mineral collecting': undefined,
  'Rock balancing': undefined,
  'Sea glass collecting': undefined,
  'Seashell collecting': undefined,
  'Stone collecting': undefined,
  'Animal fancy': undefined,
  'Axe throwing': undefined,
  'Backgammon': undefined,
  'Beauty pageants': undefined,
  'Billiards': undefined,
  'Boxing': undefined,
  'Bridge': undefined,
  'Checkers (draughts)': undefined,
  'Cheerleading': undefined,
  'Color guard': undefined,
  'Cribbage': undefined,
  'Curling': undefined,
  'Dancing': undefined,
  'Darts': undefined,
  'Debate': undefined,
  'Dominoes': undefined,
  'Eating': undefined,
  'Esports': undefined,
  'Fencing': undefined,
  'Figure Skating': undefined,
  'Go': undefined,
  'Ice hockey': undefined,
  'Judo': undefined,
  'Jujitsu': undefined,
  'Kabaddi': undefined,
  'Knowledge/word games': undefined,
  'Laser tag': undefined,
  'Mahjong': undefined,
  'Marbles': undefined,
  'Model United Nations': undefined,
  'Poker': undefined,
  'Pool': undefined,
  'Role-playing games': undefined,
  'Shogi': undefined,
  'Slot car racing': undefined,
  'Speedcubing': undefined,
  'Sport stacking': undefined,
  'Table football': undefined,
  'Table tennis': undefined,
  'Volleyball': undefined,
  'Weightlifting': undefined,
  'Wrestling': undefined,
  'Association football': undefined,
  'Australian rules football': undefined,
  'Auto racing': undefined,
  'Beach volleyball': undefined,
  'Breakdancing': undefined,
  'Cornhole': undefined,
  'Cricket': undefined,
  'Croquet': undefined,
  'Disc golf': undefined,
  'Dog sport': undefined,
  'Equestrianism': undefined,
  'Exhibition drill': undefined,
  'Field hockey': undefined,
  'Figure skating': undefined,
  'Fitness': undefined,
  'Footbag': undefined,
  'Frisbee': undefined,
  'Golfing': undefined,
  'Horsemanship': undefined,
  'Horseshoes': undefined,
  'Iceboat racing': undefined,
  'Jukskei': undefined,
  'Kart racing': undefined,
  'Knife throwing': undefined,
  'Long-distance running': undefined,
  'Marching band': undefined,
  'Mini Golf': undefined,
  'Model aircraft': undefined,
  'Quidditch': undefined,
  'Race walking': undefined,
  'Racquetball': undefined,
  'Radio-controlled car racing': undefined,
  'Roller derby': undefined,
  'Rugby league football': undefined,
  'Shooting sport': undefined,
  'Sled dog racing': undefined,
  'Softball': undefined,
  'Speed skating': undefined,
  'Squash': undefined,
  'Tennis polo': undefined,
  'Tether car': undefined,
  'Tour skating': undefined,
  'Trapshooting': undefined,
  'Triathlon': undefined,
  'UltimaQuestionAnAnserte frisbee': undefined,
  'Water polo': undefined,
  'Audiophile': undefined,
  'Learning': undefined,
  'Microscopy': undefined,
  'Shortwave listening': undefined,
  'Aircraft spotting': undefined,
  'Amateur astronomy': undefined,
  'Benchmarking': undefined,
  'Bus spotting': undefined,
  'Gongoozling': undefined,
  'People-watching': undefined,
  'Satellite watching': undefined,
  'Trainspotting': undefined,
  'Whale watching': undefined,
};