import Bank from './type';

const en: Bank = {
  _name: 'Chatapredu',
  send: 'Send',
  doYouWantToSendThisPicture: 'Do you want to send this picture?',
  doYouWantToSendThisVideo: 'Do you want to send this video?',
  name: 'Name',
  confirm: 'Confirm',
  resendConfirmationCode: 'Resend confirmation code',
  deleteChatRoom: 'Delete Chat Room',
  remove: 'Remove',
  none: 'None',
  administrator: 'Administrator',
  moderator: 'Moderator',
  searchForUser: 'Search for user',
  noUsersFound: 'No users found',
  faq: 'Frequently Asked Questions',
  requestHelp: 'Request Help',
  users: 'Users',
  generalDiscussions: 'General Discussions',
  describeYourIssue: 'Describe your Issue', 
  myIssue: 'My Issue',
  discussions: 'Discussions',
  stop: 'Stop',
  play: 'Play',
  mute: 'Mute',
  welcome: 'Welcome!',
  yes: 'Yes',
  no: 'No',
  cancel: 'Cancel',
  settings: 'Settings',
  preferences: 'Preferences',
  exit: 'Exit',
  open: 'Open',
  close: 'Close',
  openInNewTab: 'Open in new tab',
  download: 'Download',
  downloadFile: 'Download file',
  edit: 'Edit',
  help: 'Help',
  save: 'Save',
  add: 'Add',
  select: 'Select',
  selectAll: 'Select All',
  delete: 'Delete',
  deleteAll: 'Delete All',
  apply: 'Apply',
  submit: 'Submit',
  conditions: 'Conditions',
  cookiePolicy: 'Cookie Policy',
  size: 'Size',
  fileSize: 'File Size',
  duration: 'Duration',
  update: 'Update',
  more: 'More',
  touchToUpdate: 'Touch to update',
  camera: 'Camera',
  video: 'Video',
  photo: 'Photo',
  link: 'Link',
  links: 'Links',
  file: 'File',
  document: 'Document',
  audio: 'Audio',
  search: 'Search',
  back: 'Back',
  returnHome: 'Return Home',
  home: 'Home',
  rotate: 'Rotate',
  myAccount: 'My Account',
  username: 'Username',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  phoneNumber: 'Phone Number',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'E-mail',
  birthDate: 'Birth Date',
  address: 'Address',
  login: 'Login',
  signin: 'Sign-in',
  register: 'Register',
  forgotYourPassword: 'Forgot your password?',
  logout: 'Logout',
  signout: 'Sign-out',
  profile: 'Profile',
  createNewAccount: 'Create a new Account',
  noAccountRegister: 'No account? Register.',
  alreadyHaveAnAccountLogin: 'Already have an account? Login.',
  chats: 'Chats',
  status: 'Status',
  calls: 'Calls',
  typeAMessage: 'Type a message',
  contacts: 'Contacts',
  deleteForum: 'Delete Forum',
  tag: 'Tag',
  title: 'Title',
  content: 'Content',
};

export default en;