import Bank from './type';

const es: Bank = {
  welcome: '¡Saludos!',
  send: 'Enviar',
  doYouWantToSendThisPicture: '¿Deseas enviar esta imagen?',
  doYouWantToSendThisVideo: '¿Deseas enviar este vídeo?',
  name: 'Nombre',
  confirm: 'Confirmar',
  resendConfirmationCode: 'Reenviar el código de confirmación',
  deleteChatRoom: 'Borrar Sala',
  remove: 'Remover',
  none: 'Ninguno',
  administrator: 'Administrador',
  moderator: 'Moderador',
  searchForUser: 'Buscar un usuario',
  noUsersFound: 'No se encontraron usuarios',
  faq: 'Preguntas Frecuentes',
  requestHelp: 'Solicitar Ayuda',
  describeYourIssue: 'Describe tu Problema',
  myIssue: 'My problema',
  users: 'Usuarios',
  generalDiscussions: 'Discursos Generales',
  discussions: 'Discursos',
  stop: 'Detener',
  play: 'Iniciar',
  mute: 'Silencio',
  yes: 'Sí',
  no: 'No',
  cancel: 'Cancelar',
  settings: 'Ajustes',
  preferences: 'Preferencias',
  exit: 'Salir',
  open: 'Abrir',
  close: 'Cerrar',
  openInNewTab: 'Abrir en una pestaña nueva',
  download: 'Descargar',
  downloadFile: 'Descargar Archivo',
  edit: 'Editar',
  help: 'Ayuda',
  save: 'Salvar',
  add: 'Añadir',
  select: 'Seleccionar',
  selectAll: 'Seleccionar Todo',
  delete: 'Borrar',
  deleteAll: 'Borrar Todo',
  apply: 'Aplicar',
  submit: 'Enviar',
  conditions: 'Condiciones',
  cookiePolicy: 'Política de cookies',
  size: 'Tamaño',
  fileSize: 'Tamaño del archivo',
  duration: 'Duración',
  update: 'Actualizar',
  more: 'Más',
  touchToUpdate: 'Toca para actualizar',
  camera: 'Cámara',
  video: 'Vídeo',
  photo: 'Foto',
  link: 'Enlace',
  links: 'Enlaces',
  file: 'Archivo',
  document: 'Documento',
  audio: 'Audio',
  search: 'Buscar',
  back: 'Atrás',
  returnHome: 'Volver al inico',
  home: 'Inicio',
  rotate: 'Girar',
  myAccount: 'Mi Cuenta',
  username: 'Nombre de Usuario',
  password: 'Contraseña',
  confirmPassword: 'Confirmar Contraseña',
  phoneNumber: 'Número de Teléfono',
  firstName: 'Nombre',
  lastName: 'Apellido',
  email: 'Correo Electrónico',
  birthDate: 'Fecha de Nacimiento',
  address: 'Dirección Postal',
  login: 'Iniciar Sesión',
  signin: 'Iniciar Sesión',
  register: 'Registrate',
  forgotYourPassword: '¿Olvidaste tu contraseña?',
  logout: 'Cerrar Sesión',
  signout: 'Cerrar Sesión',
  profile: 'Perfil',
  createNewAccount: 'Crear cuenta nueva',
  noAccountRegister: '¿No tienes una cuenta? Registrate.',
  alreadyHaveAnAccountLogin: '¿Ya tienes una cuenta? Registrate.',
  chats: 'Conversasiones',
  status: 'Estatus',
  calls: 'Llamadas',
  typeAMessage: 'Escribe un mensaje',
  contacts: 'Contactos',
  deleteForum: 'Borrar Foro',
  tag: 'Etiqueta',
  title: 'Titulo',
  content: 'Contenido',
  reject: 'Rechazar',
  accept: 'Acceptar',
  science: 'Ciencia',
  technology: 'Technología',
  engineering: 'Ingeneria',
  medicine: 'medicina',
  math: 'Matemáticas',
  art: 'Arte',
  history: 'Historia',
  gaming: 'Juegos',
  animation: 'Animación',
  music: 'Música',
  sports: 'Deportes',
  design: 'Diseño',
  literature: 'Literatura',
  foods: 'Comida',
  automotive: 'Carros',
};

export default es;